# Site settings
title: Blog - Valentin Kirilov
email: val.kirilov[at-@]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://0.0.0.0:4000" # the base hostname & protocol for your site
twitter_username: valkirilov
github_username:  valkirilov

# Build settings
markdown: kramdown

# Default setting for templates and etc.
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Me me"

sass:
    style: :compressed